# Generated by Django 5.1.1 on 2024-12-18 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_chambre', models.CharField(choices=[('standard', 'Chambre Standard'), ('suite', 'Suite'), ('deluxe', 'Chambre Deluxe'), ('luxury', 'Chambre de Luxe')], default='standard', max_length=10)),
                ('prix_journalier', models.DecimalField(decimal_places=2, help_text='Prix par nuit en euros', max_digits=10)),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('email_client', models.EmailField(max_length=254)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, help_text='Montant total calculé en fonction du prix journalier et du nombre de nuits', max_digits=10, null=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agence.chambre')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
            },
        ),
    ]
